# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""Agentenv Environment."""

from .client import AgentenvEnv
from .models import (
    ACTION_TO_DOCUMENT,
    AgentId,
    ActionResult,
    ActionType,
    Document,
    DocumentStatus,
    DocumentType,
    Feedback,
    FeedbackType,
    LastAction,
    SkyPlanAction,
    SkyPlanObservation,
    ValidationConfig,
    WorkflowConfig,
)
from .prompts import (
    get_agent_prompt,
    get_agent_role_description,
    get_agent_quality_guidelines,
    get_agent_collaboration_guidelines,
    get_agent_common_pitfalls,
    get_agent_examples,
    get_maya_prompt,
    get_elon_prompt,
    get_jordan_prompt,
    get_robert_prompt,
    get_taylor_prompt,
    get_sam_prompt,
)
from .reward import (
    CompletionBonusCalculator,
    ContentAnalyzer,
    DEFAULT_WORKFLOW_STEPS,
    DifficultyLevel,
    EpisodeReward,
    HANDOFF_QUALITY_THRESHOLD,
    PenaltyCalculator,
    PenaltyType,
    QualityBonusCalculator,
    QualityScore,
    ReferenceLevel,
    RewardCalculator,
    RewardCache,
    RewardConfig,
    SCORE_THRESHOLD_EXCELLENT,
    SCORE_THRESHOLD_GOOD,
    SCORE_THRESHOLD_POOR,
    ScoreNormalizer,
    StepReward,
    TeamworkBonusCalculator,
    TeamworkScore,
    calculate_reward,
    clear_reward_cache,
    get_cache_size,
    reward_config,
)
from .tasks import (
    AGENT_DOCUMENTS,
    BaseGrader,
    GRADE_MAP,
    REQUIRED_DOCUMENTS,
    TASKS,
    TaskConfig,
    calculate_agent_criteria_score,
    calculate_composite_score,
    get_all_tasks,
    get_agent_checklist,
    get_task,
    get_task_summary,
    get_tasks_by_difficulty,
    grade_agent_work,
    grade_task,
)
from .workflow import (
    WORKFLOW,
    get_all_agent_ids,
    get_all_document_types,
    get_allowed_actions,
    get_agent_name,
    get_agent_role,
    get_handoff_message,
    get_next_agent,
    get_produced_documents,
    get_required_documents,
    get_workflow_entry,
    get_workflow_length,
    get_workflow_position,
    get_workflow_summary,
    is_last_agent,
    validate_action_for_agent,
)

__all__ = [
    # Core models
    "SkyPlanAction",
    "SkyPlanObservation",
    "AgentenvEnv",
    # Agent and action types
    "AgentId",
    "ActionType",
    "ActionResult",
    # Document models
    "Document",
    "DocumentType",
    "DocumentStatus",
    "Feedback",
    "FeedbackType",
    "LastAction",
    # Configuration
    "ValidationConfig",
    "WorkflowConfig",
    "ACTION_TO_DOCUMENT",
    # Workflow
    "WORKFLOW",
    "get_all_agent_ids",
    "get_all_document_types",
    "get_allowed_actions",
    "get_agent_name",
    "get_agent_role",
    "get_handoff_message",
    "get_next_agent",
    "get_produced_documents",
    "get_required_documents",
    "get_workflow_entry",
    "get_workflow_length",
    "get_workflow_position",
    "get_workflow_summary",
    "is_last_agent",
    "validate_action_for_agent",
    # Tasks
    "TASKS",
    "TaskConfig",
    "BaseGrader",
    "GRADE_MAP",
    "REQUIRED_DOCUMENTS",
    "AGENT_DOCUMENTS",
    "get_task",
    "get_all_tasks",
    "get_tasks_by_difficulty",
    "get_task_summary",
    "grade_task",
    "grade_agent_work",
    "get_agent_checklist",
    "calculate_composite_score",
    "calculate_agent_criteria_score",
    # Reward system
    "RewardCalculator",
    "RewardConfig",
    "reward_config",
    "StepReward",
    "EpisodeReward",
    "QualityScore",
    "TeamworkScore",
    "PenaltyScore",
    "ScoreNormalizer",
    "QualityBonusCalculator",
    "TeamworkBonusCalculator",
    "CompletionBonusCalculator",
    "PenaltyCalculator",
    "RewardCache",
    "ContentAnalyzer",
    "calculate_reward",
    "clear_reward_cache",
    "get_cache_size",
    # Reward system enums and constants
    "DifficultyLevel",
    "ReferenceLevel",
    "PenaltyType",
    "DEFAULT_WORKFLOW_STEPS",
    "SCORE_THRESHOLD_EXCELLENT",
    "SCORE_THRESHOLD_GOOD",
    "SCORE_THRESHOLD_POOR",
    "HANDOFF_QUALITY_THRESHOLD",
    # Agent prompts
    "get_agent_prompt",
    "get_maya_prompt",
    "get_elon_prompt",
    "get_jordan_prompt",
    "get_robert_prompt",
    "get_taylor_prompt",
    "get_sam_prompt",
    "get_agent_role_description",
    "get_agent_quality_guidelines",
    "get_agent_collaboration_guidelines",
    "get_agent_common_pitfalls",
    "get_agent_examples",
]
